version: '3.8'

services:
  db:
    image: postgres:15
    container_name: library_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_catalog
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: library_backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: library_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  db_data:
